test_drawer_pickplacecubemulti(){
    CUDA_VISIBLE_DEVICES=$1 python3.9 basic_test.py \
    --seed 0 \
    --log_path brief_test_drawer_pickplacemulti.txt \
    --skill_path store/brief_test_drawer_pickplacemulti/debug_skill \
    --demo_path store/demo_store/opendrawer_pickplacecube3_crop.npy \
    --preset_demo_path store/demo_store/opendrawer_pickplacecube2_crop.npy \
    --policy_path store/brief_test_drawer_pickplacemulti/debug_policy_{} \
    --fig_path store/brief_test_drawer_pickplacemulti/states \
    --rl_timesteps 1000 \
    --rl_batch 512 \
    --eval_traj_len 200 \
    --train_traj_len 200 \
    --collect_epoch 1 \
    --collect_len -1 \
    --collect_traj_len 200 \
    --final_goal_threshold 0.5 \
    --success_threshold 0.8 \
    --fail_success_threshold 0.8 \
    --extra_threshold 0.7 \
    --rew_threshold 0.5 \
    --reward_num 10 \
    --dso_hard_code \
    --total_iteration 50 \
    --hold_len 3 \
    --eval_epoch 1 \
    --final_eval_epoch 1 \
    --predicate_type 'tree' \
    --dense_type 'cont' \
    --n_cpu 8 \
    --obs_abs \
    --hold_rule \
    --env_name 'drawer_pickplacecubemulti' \
    --shift_positive \
    --policy_type 'sac_lag' \
    --enforce_collect \
    --lagrangian_mode \
    --reward_refine \
    --use_best \
    --min_samples_mode 'min_ratio' \
    --min_samples_leaf 0.5 \
    --last_states \
    --prune_rule \
    --prog_sim \
    --stage_reuse \
    --set_block_num 3 \
    --preset_block_num 2
}

test_push_multi(){
    CUDA_VISIBLE_DEVICES=$1 python3.9 basic_test.py \
    --seed 0 \
    --log_path brief_test_push_block3.txt \
    --skill_path store/brief_test_push_block3/debug_skill \
    --demo_path store/demo_store/pushmulti3_coll_debug_2.npy \
    --policy_path store/brief_test_push_block3/debug_policy_{} \
    --fig_path store/brief_test_push_block3/states \
    --rl_timesteps 1000 \
    --rl_batch 512 \
    --eval_traj_len 150 \
    --train_traj_len 150 \
    --collect_epoch 1 \
    --collect_len -1 \
    --collect_traj_len 150 \
    --final_goal_threshold 0.5 \
    --success_threshold 0.8 \
    --fail_success_threshold 0.8 \
    --extra_threshold 0.7 \
    --rew_threshold 0.5 \
    --reward_num 10 \
    --dso_hard_code \
    --total_iteration 50 \
    --hold_len 3 \
    --eval_epoch 1 \
    --final_eval_epoch 500 \
    --predicate_type 'tree' \
    --dense_type 'cont' \
    --n_cpu 8 \
    --obs_abs \
    --hold_rule \
    --env_name 'Fetch3Push' \
    --shift_positive \
    --policy_type 'sac_lag' \
    --enforce_collect \
    --lagrangian_mode \
    --reward_refine \
    --use_best \
    --prog_sim \
    --prune_rule \
    --min_samples_mode 'pos_ratio' \
    --min_samples_leaf 0.5 \
    --stage_reuse \
    --set_block_num 3
}

test_tower(){
    CUDA_VISIBLE_DEVICES=$1 python3.9 basic_test.py \
    --seed 0 \
    --log_path brief_test_tower5.txt \
    --skill_path store/brief_test_tower5/debug_skill \
    --demo_path store/demo_store/tower_5.npy \
    --preset_demo_path store/demo_store/tower_2.npy \
    --policy_path store/brief_test_tower5/debug_policy_{} \
    --fig_path store/brief_test_tower5/states \
    --rl_timesteps 1000 \
    --rl_batch 512 \
    --eval_traj_len 100 \
    --train_traj_len 100 \
    --collect_epoch 1 \
    --collect_len -1 \
    --collect_traj_len 100 \
    --final_goal_threshold 0.5 \
    --success_threshold 0.8 \
    --fail_success_threshold 0.8 \
    --extra_threshold 0.7 \
    --rew_threshold 0.5 \
    --reward_num 20 \
    --dso_hard_code \
    --total_iteration 50 \
    --hold_len 3 \
    --eval_epoch 1 \
    --final_eval_epoch 500 \
    --predicate_type 'tree' \
    --dense_type 'cont' \
    --n_cpu 8 \
    --obs_abs \
    --hold_rule \
    --env_name 'tower5' \
    --shift_positive \
    --shift_alpha 0.9 \
    --policy_type 'sac_lag' \
    --enforce_collect \
    --lagrangian_mode \
    --reward_refine \
    --use_best \
    --min_samples_mode 'pos_ratio' \
    --min_samples_leaf 0.5 \
    --stage_reuse \
    --set_block_num 5 \
    --preset_block_num 2
}

test_pickplace_multi_4(){
    CUDA_VISIBLE_DEVICES=$1 python3.9 basic_test.py \
    --seed 0 \
    --log_path brief_test_pickplace_multi.txt \
    --skill_path store/brief_test_pickplace_multi/debug_skill \
    --demo_path store/demo_store/custom_pickplacemulti_block4_clean.npy \
    --preset_demo_path store/demo_store/custom_pickplacemulti_simple_block2.npy \
    --policy_path store/brief_test_pickplace_multi/debug_policy_{} \
    --fig_path store/brief_test_pickplace_multi/states \
    --rl_timesteps 1000 \
    --rl_batch 512 \
    --eval_traj_len 100 \
    --train_traj_len 100 \
    --collect_epoch 1 \
    --collect_len -1 \
    --collect_traj_len 100 \
    --final_goal_threshold 0.5 \
    --success_threshold 0.8 \
    --fail_success_threshold 0.8 \
    --extra_threshold 0.7 \
    --rew_threshold 0.5 \
    --reward_num 10 \
    --dso_hard_code \
    --total_iteration 50 \
    --hold_len 3 \
    --eval_epoch 1 \
    --final_eval_epoch 500 \
    --predicate_type 'tree' \
    --dense_type 'cont' \
    --n_cpu 8 \
    --obs_abs \
    --hold_rule \
    --env_name 'pickmulti4' \
    --shift_positive \
    --policy_type 'sac_lag' \
    --enforce_collect \
    --lagrangian_mode \
    --reward_refine \
    --use_best \
    --min_samples_mode 'pos_ratio' \
    --min_samples_leaf 0.5 \
    --stage_reuse \
    --set_block_num 4 \
    --preset_block_num 2
}

test_push_multi 0
test_tower 0
test_pickplace_multi_4 0
